### PR TITLE
Adds support for label order

### PR DESCRIPTION
**Pull request by exocom**
## what
* Adding support for label_order so the "name" & "id" can be customized as intended by the label module.

## why
* The name of the resource was x-dev-1-dev-1 because of how we do tagging.

### CODE REVIEW

**Comment by exocom** [comment]
Can anyone help look at the build? It looks like some infrastructure got left over and needs to be manually removed.

**Comment by Gowiem** [comment]
@exocom Thanks for the contribution! Released as [0.5.0](https://github.com/cloudposse/terraform-aws-elasticache-memcached/releases/tag/0.5.0).

**Pull request merged**
