### PR TITLE
fix conflict with using custom security group

### PR DESCRIPTION
**Pull request by dmytrozhivotovsky**
## what
* Remove join splat on module.security_group_arn

## why
* Fix conflict with using custom security group in `associated_security_group_ids` and argument `create_security_group` is false

## references
* N/A

### CODE REVIEW

**Review by aknysh — APPROVED** [review]

**Comment by aknysh** [comment]
@dmytrozhivotovsky 

please update TF version in https://github.com/cloudposse/terraform-aws-elasticache-memcached/blob/master/examples/complete/versions.tf#L2

to be consistent with the version in the module

```
terraform {
  required_version = ">= 0.14.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.26"
    }
  }
```

the `null` provider is not used and not required

Then please run the following commands from the root of the repo:

```
make init
make github/init
make readme
```

and commit the changes

Thank you

**Review by aknysh — DISMISSED** [review]
please see comments

**Review by nitrocode — APPROVED** [review]

**Review by nitrocode — APPROVED** [review]

**Comment by nitrocode** [comment]
I see this error in `test/terratest`. It could be a stale resource that may be cleaned up by tomorrow.

```hcl
TestExamplesComplete 2022-06-18T15:03:50Z logger.go:66: Error: creating ElastiCache Subnet Group (eg-test-memcached-test): CacheSubnetGroupAlreadyExists: Cache subnet group eg-test-memcached-test already exists.
TestExamplesComplete 2022-06-18T15:03:50Z logger.go:66: 	status code: 400, request id: 137da1d1-301e-4410-9a8d-0d5f08dd8511
TestExamplesComplete 2022-06-18T15:03:50Z logger.go:66: 
TestExamplesComplete 2022-06-18T15:03:50Z logger.go:66:   on ../../main.tf line 84, in resource "aws_elasticache_subnet_group" "default":
TestExamplesComplete 2022-06-18T15:03:50Z logger.go:66:   84: resource "aws_elasticache_subnet_group" "default" {
TestExamplesComplete 2022-06-18T15:03:50Z logger.go:66: 
TestExamplesComplete 2022-06-18T15:03:50Z logger.go:66: 
TestExamplesComplete 2022-06-18T15:03:50Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; 
Error: creating ElastiCache Subnet Group (eg-test-memcached-test): CacheSubnetGroupAlreadyExists: Cache subnet group eg-test-memcached-test already exists.
	status code: 400, request id: 137da1d1-301e-4410-9a8d-0d5f08dd8511
  on ../../main.tf line 84, in resource "aws_elasticache_subnet_group" "default":
  84: resource "aws_elasticache_subnet_group" "default" {
}
    apply.go:15: 
        	Error Trace:	apply.go:15
        	            				examples_complete_test.go:26
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; 
Error: creating ElastiCache Subnet Group (eg-test-memcached-test): CacheSubnetGroupAlreadyExists: Cache subnet group eg-test-memcached-test already exists.
        	            		status code: 400, request id: 137da1d1-301e-4410-9a8d-0d5f08dd8511
  on ../../main.tf line 84, in resource "aws_elasticache_subnet_group" "default":
        	            	  84: resource "aws_elasticache_subnet_group" "default" {
}
```

I'll try rerunning the tests once more today.

**Comment by z0rc** [comment]
Any update on this?

**Pull request closed without merging**
