### PR TITLE
Pass apply_immediately variable to aws_elasticache_cluster resource

### LINKED ISSUE #12: "apply_immediately" variable has no effect
When setting `apply_immediately` on the module, the node updates on the cluster are still pending in AWS based on the default maintenance window.

I believe this is because the variable is not being passed to the `aws_elasticache_cluster` resource.

### PR DESCRIPTION
**Pull request by cdaloisio**
Fixes #12

### CODE REVIEW

**Review by jamengual — DISMISSED** [review]

**Comment by jamengual** [comment]
@cdaloisio could you rebase?

**Comment by cdaloisio** [comment]
Sure thing @jamengual :+1: 
Re-running tests now also!

**Comment by cdaloisio** [comment]
Hmm, I didn't see the emoji from the `cloudpossebot` acknowledge the test command. Checking the Github actions I saw this error.
 ```
Command 'test' is not configured for the user's permission level 'none'.
```
Perhaps this is a recent change to not prevent non-authorized users from triggering particular commands? In any case, after the tests have run successfully, this should be OK to merge.

**Review by jamengual — APPROVED** [review]

**Pull request merged**
