### PR TITLE
configurable memcached parameter group

### PR DESCRIPTION
**Pull request by wiseelf**
## what
* added new variable parameter
* value of variable max_item_size was added as default value to parameter
* added dynamic block to aws_elasticache_parameter_group resource

## why
* To add ability to configure Memcached parameter group.

### CODE REVIEW

**Comment by wiseelf** [comment]
@r351574nc3 @milldr could you please review this PR?

**Review by max-lobur — DISMISSED** [review]

**Comment by max-lobur** [comment]
I believe the master branch needs to be updated/syncd with our latest to make this work

**Comment by PaulMiles-cnic** [comment]
@max-lobur @milldr Hi Guys - Is there any movement on this feature request ?

Independently, we've forked and created something almost identical so there is a definite need for this parameter change.

**Pull request closed without merging**
